version: '2'
services:
    postgres:
      image: postgres:9.6.7
      restart: always
      environment:
       - "POSTGRES_USER=${DOCKER_GOGS_DB_USER}"
       - "POSTGRES_PASSWORD=${DOCKER_GOGS_DB_PASSWORD}"
       - "POSTGRES_DB=${DOCKER_GOGS_DB}"
      volumes:
       - "db-data:/var/lib/postgresql/data"
      networks:
       - gogs
    gogs:
      image: gogs/gogs:latest
      restart: always
      ports:
       - "10022:22"
       - "3000:3000"
      links:
       - postgres
      environment:
       - "RUN_CROND=true"
      networks:
       - gogs
      volumes:
       - "gogs-data:/data"
      depends_on:
       - postgres

networks:
    gogs:
      driver: bridge

volumes:
    db-data:
      driver: local
    gogs-data:
      driver: local
